---
- hosts: all
  remote_user: ansible
  tasks:
    - name: ensure centos base 6 and epel form aliyun is enabled
      get_url: url=http://mirrors.aliyun.com/repo/{{ item.src }} dest=/etc/yum.repos.d/{{ item.dest }}
      with_items:
        - {src: 'Centos-6.repo', dest: 'CentOS-Base.repo'}
        - {src: 'epel-6.repo', dest: 'epel.repo'}
      become: Ture

    - name: yum repository makecache
      shell: yum makecache

    - name : ensure common used tools is installed, like vim, ntpdate
      yum:
        name: '{{ item }}'
        with_items:
          - vim
          - ntpdate
          - libselinux-python
          - libsemanage-python
        state: present
        become: Ture

    - name: configration ntpdate cronjob,ensure server time is sync to ntp server
      cron:
        name: sync time
        job: /usr/sbin/ntpdate  195.13.1.153
        minute: "*/5"
        state: present

    - name: ensure the motd file is present
      template:
        src: motd
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
      become: Ture

    - name: ensure hostname is the same of the inventory
      hostname:
        name: '{{  inventory_hostname }}'
      become: Ture
